management:
  endpoints:
    web:
      exposure:
        include: refresh

runtime:
  props:
    unavailable: false
    latency-in-milli: 10

server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: service-conta

  datasource:
    url: jdbc:postgresql://postgres:5432/db_conta #banco especifico
    username: admin
    password: admin123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

camel:
  routes:
    direct: 
      consultar-conta: direct:consultar-conta
      criar-conta: direct:criar-conta
    kafka:
      notificar-conta: kafka:notificar-conta?brokers={{camel.component.kafka.brokers}}

  component:
    kafka:
      autoCreateTopics: true
      brokers: broker:9093 # nome do serviço
      group-id: service-conta
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  dataformat:
    jackson:
      auto-discover-object-mapper: true